version: '3.7'
services:

  
  ci-app-front:
    build:
      context: .
    container_name: ci-angular
    image: docker.io/malekhm/crudtutofront:latest
    ports:
      - "8888:80"
    networks:
      - ci-network
      
  ci-db:
    container_name: ci-db
    image: mysql:8.0
    networks:
      - ci-network
    environment:
      - MYSQL_USER=malek
      - MYSQL_PASSWORD=Malek1+3
      - MYSQL_DATABASE=tpachato
      - MYSQL_ROOT_PASSWORD=Malek1+2
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  ci-app:
    build:
      context: .
    container_name: ci-spring
    image: docker.io/malekhm/spring:latest
    ports:
      - "8089:8089"
    networks:
      - ci-network
    depends_on:
      - ci-db
    environment:
      - MYSQL_HOST=ci-db
      - MYSQL_USERNAME=malek
      - MYSQL_PASSWORD=Malek1+3
      - MYSQL_DATABASE=tpachato
      - MYSQL_PORT=3306
      

networks:
  ci-network:
    name: ci-network

volumes:
  dbvol:
